### ISSUE TITLE
Error: Cannot find module 'crash-reporter'

### ISSUE THREAD

**Issue by fghhfg** [CodyPearce/notetron#1]
win7 64bit en, nodejs v6:
```
git clone https://github.com/CodyPearce/notetron.git
cd calctron
npm install
...
λ npm start

> notetron@0.1.0 start C:\Users\user\Downloads\notetron-master
> electron .


App threw an error during load
Error: Cannot find module 'crash-reporter'
    at Module._resolveFilename (module.js:455:15)
    at Function.Module._resolveFilename (C:\Users\user\AppData\Roaming\npm\node_modules\electron\dist\resources\electron.asar\common\reset-search-paths.js:35:12)
    at Function.Module._load (module.js:403:25)
    at Module.require (module.js:483:17)
    at require (internal/module.js:20:19)
    at Object.<anonymous> (C:\Users\user\Downloads\notetron-master\main.js:7:1)
    at Module._compile (module.js:556:32)
    at Object.Module._extensions..js (module.js:565:10)
    at Module.load (module.js:473:32)
    at tryModuleLoad (module.js:432:12)

```

**Comment by codypearce** [comment]
Should be fixed now
